import re

file_path = "/Users/piyushraj/Desktop/Ojas/src/i18n/translations.ts"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

# Greetings and Menu data for 12 languages
GREETINGS_DATA = {
    "en": {
        "greetingMorning": "Good Morning, Farmer ☀️",
        "greetingAfternoon": "Good Afternoon, Farmer 🌤️",
        "greetingEvening": "Good Evening, Farmer 🌆",
        "greetingNight": "Good Night, Farmer 🌙",
        "welcomeToOjas": "Welcome to OJAS",
        "splashTagline1": "CLEAN ENERGY • COOLER HARVESTS • BRIGHTER TOMORROWS",
        "splashTagline2": "FOR A FRESHER INDIA • 100% SOLAR & WIND POWERED",
        "enterChamber": "Enter Cold Chamber →",
        "menuTitle": "Navigation & Chamber Menu",
        "menuSubtitle": "Solar Cold Chain SC-001 • Nashik",
        "allScreens": "ALL SYSTEM SCREENS",
        "quickControls": "QUICK CONTROLS",
        "switchLanguage": "Language / भाषा",
        "themeModeTitle": "Visual Theme",
        "chamberStatusOnline": "Live Sensor Mesh Online",
        "chamberStatusOffline": "Chamber Offline Simulation",
        "supportHotline": "24/7 Kisan Helpline: 1800-OJAS-AGRI",
    },
    "hi": {
        "greetingMorning": "सुप्रभात, किसान भाई ☀️",
        "greetingAfternoon": "शुभ दोपहर, किसान भाई 🌤️",
        "greetingEvening": "शुभ संध्या, किसान भाई 🌆",
        "greetingNight": "शुभ रात्रि, किसान भाई 🌙",
        "welcomeToOjas": "ओजस (OJAS) में आपका स्वागत है",
        "splashTagline1": "स्वच्छ ऊर्जा • शीतल उपज • उज्ज्वल कल",
        "splashTagline2": "एक ताज़ा भारत के लिए • 100% सौर एवं पवन ऊर्जा",
        "enterChamber": "कोल्ड स्टोरेज में प्रवेश करें →",
        "menuTitle": "मेन्यू और नियंत्रण",
        "menuSubtitle": "सोलर कोल्ड स्टोरेज SC-001 • नासिक",
        "allScreens": "सभी सिस्टम स्क्रीन",
        "quickControls": "त्वरित सेटिंग्स",
        "switchLanguage": "भाषा बदलें",
        "themeModeTitle": "थीम मोड",
        "chamberStatusOnline": "लाइव सेंसर मेष सक्रिय",
        "chamberStatusOffline": "ऑफलाइन सिमुलेशन",
        "supportHotline": "24/7 किसान हेल्पलाइन: 1800-OJAS-AGRI",
    },
    "mr": {
        "greetingMorning": "शुभ सकाळ, शेतकरी बांधव ☀️",
        "greetingAfternoon": "शुभ दुपार, शेतकरी बांधव 🌤️",
        "greetingEvening": "शुभ संध्याकाळ, शेतकरी बांधव 🌆",
        "greetingNight": "शुभ रात्री, शेतकरी बांधव 🌙",
        "welcomeToOjas": "ओजस (OJAS) मध्ये आपले स्वागत आहे",
        "splashTagline1": "स्वच्छ ऊर्जा • ताजी पिके • उज्ज्वल भविष्य",
        "splashTagline2": "ताजा भारतासाठी • 100% सौर व पवन ऊर्जा",
        "enterChamber": "कोल्ड स्टोरेजमध्ये प्रवेश करा →",
        "menuTitle": "मेनू आणि नेव्हिगेशन",
        "menuSubtitle": "सौर कोल्ड स्टोरेज SC-001 • नाशिक",
        "allScreens": "सर्व सिस्टम स्क्रीन्स",
        "quickControls": "द्रुत नियंत्रणे",
        "switchLanguage": "भाषा बदला",
        "themeModeTitle": "थीम निवडा",
        "chamberStatusOnline": "थेट सेन्सर नेटवर्क सक्रिय",
        "chamberStatusOffline": "ऑफलाइन सिम्युलेशन",
        "supportHotline": "24/7 शेतकरी हेल्पलाइन: 1800-OJAS-AGRI",
    },
    "bn": {
        "greetingMorning": "সুপ্রভাত, কৃষক বন্ধু ☀️",
        "greetingAfternoon": "শুভ অপরাহ্ন, কৃষক বন্ধু 🌤️",
        "greetingEvening": "শুভ সন্ধ্যা, কৃষক বন্ধু 🌆",
        "greetingNight": "শুভ রাত্রি, কৃষক বন্ধু 🌙",
        "welcomeToOjas": "ওজস (OJAS)-এ আপনাকে স্বাগতম",
        "splashTagline1": "পরিচ্ছন্ন শক্তি • তাজা ফসল • উজ্জ্বল ভবিষ্যৎ",
        "splashTagline2": "তাজা ভারতের জন্য • ১০০% সৌর ও বায়ু শক্তি",
        "enterChamber": "কোল্ড স্টোরেজে প্রবেশ করুন →",
        "menuTitle": "মেনু ও নেভিগেশন",
        "menuSubtitle": "সোলার কোল্ড স্টোরেজ SC-001",
        "allScreens": "সকল সিস্টেম স্ক্রিন",
        "quickControls": "দ্রুত সেটিংস",
        "switchLanguage": "ভাষা পরিবর্তন",
        "themeModeTitle": "থিম মোড",
        "chamberStatusOnline": "লাইভ সেন্সর নেটওয়ার্ক সক্রিয়",
        "chamberStatusOffline": "অফলাইন সিমুলেশন",
        "supportHotline": "২৪/৭ কৃষক হেল্পলাইন: 1800-OJAS-AGRI",
    },
    "te": {
        "greetingMorning": "శుభోదయం, రైతు సోదరా ☀️",
        "greetingAfternoon": "శుభ మధ్యాహ్నం, రైతు సోదరా 🌤️",
        "greetingEvening": "శుభ సాయంత్రం, రైతు సోదరా 🌆",
        "greetingNight": "శుభరాత్రి, రైతు సోదరా 🌙",
        "welcomeToOjas": "ఓజస్ (OJAS) కు స్వాగతం",
        "splashTagline1": "స్వచ్ఛ ఇంధనం • తాజా పంటలు • ఉజ్వల భవిష్యత్తు",
        "splashTagline2": "తాజా భారతదేశం కోసం • 100% సౌర & పవన శక్తి",
        "enterChamber": "కోల్డ్ స్టోరేజ్‌లోకి ప్రవేశించండి →",
        "menuTitle": "మెనూ & నావిగేషన్",
        "menuSubtitle": "సోలార్ కోల్డ్ స్టోరేజ్ SC-001",
        "allScreens": "అన్ని సిస్టమ్ స్క్రీన్‌లు",
        "quickControls": "త్వరిత నియంత్రణలు",
        "switchLanguage": "భాష మార్చండి",
        "themeModeTitle": "థీమ్ ఎంపిక",
        "chamberStatusOnline": "లైవ్ సెన్సార్ మెష్ ఆన్‌లైన్",
        "chamberStatusOffline": "ఆఫ్‌లైన్ సిమ్యులేషన్",
        "supportHotline": "24/7 రైతు హెల్ప్‌లైన్: 1800-OJAS-AGRI",
    },
    "ta": {
        "greetingMorning": "காலை வணக்கம், விவசாய தோழரே ☀️",
        "greetingAfternoon": "மதிய வணக்கம், விவசாய தோழரே 🌤️",
        "greetingEvening": "மாலை வணக்கம், விவசாய தோழரே 🌆",
        "greetingNight": "இனிய இரவு, விவசாய தோழரே 🌙",
        "welcomeToOjas": "ஓஜஸ் (OJAS) க்கு நல்வரவு",
        "splashTagline1": "தூய எரிசக்தி • புதிய அறுவடை • ஒளிமயமான எதிர்காலம்",
        "splashTagline2": "புதிய இந்தியாவிற்காக • 100% சூரிய & காற்று மின்சாரம்",
        "enterChamber": "குளிர்பதன கிடங்கிற்குள் நுழையுங்கள் →",
        "menuTitle": "மெனு & வழிசெலுத்தல்",
        "menuSubtitle": "சூரிய குளிர்பதன கிடங்கு SC-001",
        "allScreens": "அனைத்து திரைகள்",
        "quickControls": "விரைவு கட்டுப்பாடுகள்",
        "switchLanguage": "மொழி மாற்றம்",
        "themeModeTitle": "தீம் தேர்வு",
        "chamberStatusOnline": "நேரடி சென்சார் இயங்குகிறது",
        "chamberStatusOffline": "ஆஃப்லைன் உருவகப்படுத்துதல்",
        "supportHotline": "24/7 உழவர் உதவி எண்: 1800-OJAS-AGRI",
    },
    "gu": {
        "greetingMorning": "શુભ સવાર, ખેડૂત મિત્ર ☀️",
        "greetingAfternoon": "શુભ બપોર, ખેડૂત મિત્ર 🌤️",
        "greetingEvening": "શુભ સાંજ, ખેડૂત મિત્ર 🌆",
        "greetingNight": "શુભ રાત્રિ, ખેડૂત મિત્ર 🌙",
        "welcomeToOjas": "ઓજસ (OJAS) માં આપનું સ્વાગત છે",
        "splashTagline1": "સ્વચ્છ ઊર્જા • તાજો પાક • ઉજ્જવળ ભવિષ્ય",
        "splashTagline2": "તાજા ભારત માટે • 100% સૌર અને પવન ઊર્જા",
        "enterChamber": "કોલ્ડ સ્ટોરેજમાં પ્રવેશ કરો →",
        "menuTitle": "મેનૂ અને નેવિગેશન",
        "menuSubtitle": "સોલર કોલ્ડ સ્ટોરેજ SC-001",
        "allScreens": "તમામ સિસ્ટમ સ્ક્રીન",
        "quickControls": "ઝડપી સેટિંગ્સ",
        "switchLanguage": "ભાષા બદલો",
        "themeModeTitle": "થીમ મોડ",
        "chamberStatusOnline": "લાઇવ સેન્સર નેટવર્ક સક્રિય",
        "chamberStatusOffline": "ઑફલાઇન સિમ્યુલેશન",
        "supportHotline": "24/7 ખેડૂત હેલ્પલાઇન: 1800-OJAS-AGRI",
    },
    "kn": {
        "greetingMorning": "ಶುಭೋದಯ, ರೈತ ಮಿತ್ರರೇ ☀️",
        "greetingAfternoon": "ಶುಭ ಮಧ್ಯಾಹ್ನ, ರೈತ ಮಿತ್ರರೇ 🌤️",
        "greetingEvening": "ಶುಭ ಸಂಜೆ, ರೈತ ಮಿತ್ರರೇ 🌆",
        "greetingNight": "ಶುಭ ರಾತ್ರಿ, ರೈತ ಮಿತ್ರರೇ 🌙",
        "welcomeToOjas": "ಓಜಸ್ (OJAS) ಗೆ ಸ್ವಾಗತ",
        "splashTagline1": "ಸ್ವಚ್ಛ ಇಂಧನ • ತಾಜಾ ಬೆಳೆಗಳು • ಉಜ್ವಲ ಭವಿಷ್ಯ",
        "splashTagline2": "ತಾಜಾ ಭಾರತಕ್ಕಾಗಿ • 100% ಸೌರ ಮತ್ತು ಪವನ ಶಕ್ತಿ",
        "enterChamber": "ಕೋಲ್ಡ್ ಸ್ಟೋರೇಜ್ ಪ್ರವೇಶಿಸಿ →",
        "menuTitle": "ಮೆನು & ಸಂಚರಣೆ",
        "menuSubtitle": "ಸೌರ ಕೋಲ್ಡ್ ಸ್ಟೋರೇಜ್ SC-001",
        "allScreens": "ಎಲ್ಲಾ ಸಿಸ್ಟಮ್ ಪರದೆಗಳು",
        "quickControls": "ತ್ವರಿತ ನಿಯಂತ್ರಣಗಳು",
        "switchLanguage": "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
        "themeModeTitle": "ಥೀಮ್ ಮೋಡ್",
        "chamberStatusOnline": "ಲೈವ್ ಸೆನ್ಸರ್ ನೆಟ್‌ವರ್ಕ್ ಸಕ್ರಿಯ",
        "chamberStatusOffline": "ಆಫ್‌ಲೈನ್ ಸಿಮ್ಯುಲೇಶನ್",
        "supportHotline": "24/7 ರೈತ ಸಹಾಯವಾಣಿ: 1800-OJAS-AGRI",
    },
    "ml": {
        "greetingMorning": "സുപ്രഭാതം, കർഷക സുഹൃത്തേ ☀️",
        "greetingAfternoon": "ശുഭ ഉച്ചതിരിഞ്ഞ്, കർഷക സുഹൃത്തേ 🌤️",
        "greetingEvening": "ശുഭ സായാഹ്നം, കർഷക സുഹൃത്തേ 🌆",
        "greetingNight": "ശുഭ രാത്രി, കർഷക സുഹൃത്തേ 🌙",
        "welcomeToOjas": "ഓജസ് (OJAS)-ലേക്ക് സ്വാഗതം",
        "splashTagline1": "ശുദ്ധമായ ഊർജ്ജം • പുതിയ വിളവെടുപ്പ് • ശോഭനമായ ഭാവി",
        "splashTagline2": "പുതിയ ഇന്ത്യയ്ക്കായി • 100% സൗരോർജ്ജവും കാറ്റാടിയും",
        "enterChamber": "കോൾഡ് സ്റ്റോറേജിൽ പ്രവേശിക്കുക →",
        "menuTitle": "മെനുവും നിയന്ത്രണങ്ങളും",
        "menuSubtitle": "സോളാർ കോൾഡ് സ്റ്റോറേജ് SC-001",
        "allScreens": "എല്ലാ സിസ്റ്റം സ്ക്രീനുകളും",
        "quickControls": "ദ്രുത നിയന്ത്രണങ്ങൾ",
        "switchLanguage": "ഭാഷ മാറ്റുക",
        "themeModeTitle": "തീം മോഡ്",
        "chamberStatusOnline": "ലൈവ് സെൻസർ മെഷ് ഓൺലൈൻ",
        "chamberStatusOffline": "ഓഫ്‌ലൈൻ സിമുലേഷൻ",
        "supportHotline": "24/7 കർഷക ഹെൽപ്പ്‌ലൈൻ: 1800-OJAS-AGRI",
    },
    "pa": {
        "greetingMorning": "ਸ਼ੁਭ ਸਵੇਰ, ਕਿਸਾਨ ਵੀਰੋ ☀️",
        "greetingAfternoon": "ਸ਼ੁਭ ਦੁਪਹਿਰ, ਕਿਸਾਨ ਵੀਰੋ 🌤️",
        "greetingEvening": "ਸ਼ੁਭ ਸ਼ਾਮ, ਕਿਸਾਨ ਵੀਰੋ 🌆",
        "greetingNight": "ਸ਼ੁਭ ਰਾਤ, ਕਿਸਾਨ ਵੀਰੋ 🌙",
        "welcomeToOjas": "ਓਜਸ (OJAS) ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ",
        "splashTagline1": "ਸਵੱਛ ਊਰਜਾ • ਤਾਜ਼ੀ ਫ਼ਸਲ • ਸੁਨਹਿਰੀ ਭਵਿੱਖ",
        "splashTagline2": "ਤਾਜ਼ੇ ਭਾਰਤ ਲਈ • 100% ਸੌਰ ਅਤੇ ਪਵਨ ਊਰਜਾ",
        "enterChamber": "ਕੋਲਡ ਸਟੋਰੇਜ ਵਿੱਚ ਦਾਖਲ ਹੋਵੋ →",
        "menuTitle": "ਮੇਨੂ ਅਤੇ ਨੈਵੀਗੇਸ਼ਨ",
        "menuSubtitle": "ਸੋਲਰ ਕੋਲਡ ਸਟੋਰੇਜ SC-001",
        "allScreens": "ਸਾਰੀਆਂ ਸਿਸਟਮ ਸਕ੍ਰੀਨਾਂ",
        "quickControls": "ਤੁਰੰਤ ਕੰਟਰੋਲ",
        "switchLanguage": "ਭਾਸ਼ਾ ਬਦਲੋ",
        "themeModeTitle": "ਥੀਮ ਮੋਡ",
        "chamberStatusOnline": "ਲਾਈਵ ਸੈਂਸਰ ਨੈੱਟਵਰਕ ਐਕਟਿਵ",
        "chamberStatusOffline": "ਆਫ਼ਲਾਈਨ ਸਿਮੂਲੇਸ਼ਨ",
        "supportHotline": "24/7 ਕਿਸਾਨ ਹੈਲਪਲਾਈਨ: 1800-OJAS-AGRI",
    },
    "or": {
        "greetingMorning": "ଶୁଭ ସକାଳ, ଚାଷୀ ଭାଇ ☀️",
        "greetingAfternoon": "ଶୁଭ ଅପରାହ୍ନ, ଚାଷୀ ଭାଇ 🌤️",
        "greetingEvening": "ଶୁଭ ସନ୍ଧ୍ୟା, ଚାଷୀ ଭାଇ 🌆",
        "greetingNight": "ଶୁଭ ରାତ୍ରି, ଚାଷୀ ଭାଇ 🌙",
        "welcomeToOjas": "ଓଜସ (OJAS) କୁ ସ୍ଵାଗତ",
        "splashTagline1": "ସ୍ୱଚ୍ଛ ଶକ୍ତି • ତାଜା ଫସଲ • ଉଜ୍ଜ୍ୱଳ ଭବିଷ୍ୟତ",
        "splashTagline2": "ଏକ ତାଜା ଭାରତ ପାଇଁ • 100% ସୌର ଓ ପବନ ଶକ୍ତି",
        "enterChamber": "କୋଲ୍ଡ ଷ୍ଟୋରେଜରେ ପ୍ରବେଶ କରନ୍ତୁ →",
        "menuTitle": "ମେନୁ ଏବଂ ନିୟନ୍ତ୍ରଣ",
        "menuSubtitle": "ସୌର କୋଲ୍ଡ ଷ୍ଟୋରେଜ SC-001",
        "allScreens": "ସମସ୍ତ ସିଷ୍ଟମ ସ୍କ୍ରିନ",
        "quickControls": "ଦ୍ରୁତ ନିୟନ୍ତ୍ରଣ",
        "switchLanguage": "ଭାଷା ବଦଳାନ୍ତୁ",
        "themeModeTitle": "ଥିମ୍ ମୋଡ୍",
        "chamberStatusOnline": "ଲାଇଭ୍ ସେନ୍ସର ମେଶ୍ ସକ୍ରିୟ",
        "chamberStatusOffline": "ଅଫଲାଇନ୍ ସିମ୍ୟୁଲେସନ୍",
        "supportHotline": "24/7 କୃଷକ ହେଲ୍ପଲାଇନ୍: 1800-OJAS-AGRI",
    },
    "hinglish": {
        "greetingMorning": "Good Morning, Kisan Bhai ☀️",
        "greetingAfternoon": "Good Afternoon, Kisan Bhai 🌤️",
        "greetingEvening": "Good Evening, Kisan Bhai 🌆",
        "greetingNight": "Good Night, Kisan Bhai 🌙",
        "welcomeToOjas": "Welcome to OJAS (ओजस)",
        "splashTagline1": "Clean Energy • Cooler Harvests • Brighter Tomorrows",
        "splashTagline2": "For a Fresher India • 100% Solar & Wind Powered",
        "enterChamber": "Enter Cold Chamber →",
        "menuTitle": "Navigation & Chamber Menu",
        "menuSubtitle": "Solar Cold Chain SC-001 • Nashik",
        "allScreens": "ALL SYSTEM SCREENS",
        "quickControls": "QUICK SETTINGS",
        "switchLanguage": "Switch Language / भाषा",
        "themeModeTitle": "Theme Mode",
        "chamberStatusOnline": "Live Sensor Mesh Online",
        "chamberStatusOffline": "Chamber Offline Simulation",
        "supportHotline": "24/7 Kisan Helpline: 1800-OJAS-AGRI",
    }
}

for lang, kvs in GREETINGS_DATA.items():
    # Find lang block: e.g. "  en: {"
    pattern = rf'(  {lang}:\s*\{{)'
    match = re.search(pattern, content)
    if match:
        insert_str = "\n" + "\n".join([f'    {k}: {repr(v)},' for k, v in kvs.items()])
        idx = match.end()
        content = content[:idx] + insert_str + content[idx:]
        print(f"Updated {lang} with {len(kvs)} keys")
    else:
        print(f"Warning: Could not find block for {lang}")

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Successfully injected all greetings and menu keys into translations.ts!")
